name: Auto Report

on: 
  schedule:
    # every 8 hours
    - cron: '0 */10 * * *'
  workflow_dispatch:
      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go mod download

    - name: Run
      run: go run .
      env:
        student_id: ${secrets.STUDENT_ID}
        password: ${secrets.PASSWORD}
