name: Auto Report

on: 
  schedule:
    # Between eight and nine, every fifteen minutes
    - cron: '0/15 0-1 * * *'
  workflow_dispatch:
      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go mod download

    - name: Run
      run: go run .
      env:
        student_id: ${{secrets.STUDENT_ID}}
        password: ${{secrets.PASSWORD}}
