name: Auto Report

on: 
  schedule:
    # Between 21 - 22, every fifteen minutes
    - cron: '0/15 13-14 * * *'
  workflow_dispatch:
      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go mod download

    - name: Run
      run: go run .
      env:
        student_id: ${{secrets.STUDENT_ID}}
        password: ${{secrets.PASSWORD}}
    
    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: update report log'
        file_path: report.log
        commit_author: Github Action <actions@github.com>
