name: Auto Report

on: 
  schedule:
    # Between nine and ten, every fifteen minutes
    - cron: '0/15 0-1 * * *'
  workflow_dispatch:
      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go mod download

    - name: Run
      run: go run .
      uses: tefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: update report log'
        file_path: report.log
      env:
        student_id: ${{secrets.STUDENT_ID}}
        password: ${{secrets.PASSWORD}}
